(function(z){
var CL=function(a,b,c){b="new"===(b||a.nd);return c?(a=a.d.u.v().get(z.U.Gp),b?-1:-a):a.fl+(b?-1:1)};var DL=function(a){z.Ov.call(this,a);this.fl=0;this.nd="new"};var EL=function(a,b){a.QX=b};
var FL=function(a){return(0,z.Q)('\x3cdiv class\x3d"fyre '+(a.Jd?"fyre-liveblog ":"")+(a.bh?"fyre-livechat ":"")+(a.kU?"fyre-bootstrap ":"")+(a.se?"fyre-mobile":"")+'"\x3e\x3cdiv class\x3d"fyre-widget '+(a.Sa?"fyre-avatar-disabled":"")+'"\x3e'+(0,z.Q)('\x3cdiv class\x3d"fyre-featured-content-wrapper" style\x3d"display: none"\x3e\x3c/div\x3e')+'\x3cdiv class\x3d"fyre-stream-stats"\x3e\x3cdiv class\x3d"fyre-comment-count"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-help"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-auth"\x3e\x3cdiv class\x3d"fyre-login-bar"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-live-container"\x3e\x3cdiv class\x3d"fyre-livecount"\x3e\x3c/div\x3e'+
(a.Sa?"":'\x3cdiv class\x3d"fyre-listener-avatars"\x3e\x3c/div\x3e')+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-editor"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-input-box-collapsed"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-comment-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-top-content-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-thread-breakout-stream"\x3e\x3c/div\x3e'+(a.ro?'\x3cdiv class\x3d"fyre-archive-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-archive-stream"\x3e\x3c/div\x3e':
"")+'\x3cdiv class\x3d"fyre-stream-menu-container"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e')};var GL=function(a){return(0,z.Q)('\x3ca href\x3d"'+z.R(z.S(a.Aa))+'" title\x3d"'+z.R(a.da)+'" data-id\x3d"'+z.R(a.id)+'" class\x3d"fyre-follower fyre-follower-'+z.R(a.TT)+'"\x3e\x3cimg src\x3d"'+z.R(z.S(a.zd))+'" alt\x3d"'+z.R(a.da)+'" onerror\x3d"javascript:this.src\x3d\''+z.R(z.gp(a.cc))+"';\" /\x3e\x3c/a\x3e")};
var HL=function(a){return(0,z.Q)(z.gr(a)+'\x3cdiv class\x3d"fyre-archive-stream-sort fyre-stream-sort"\x3e\x3ch3 class\x3d"fyre-archive-stream-title"\x3e\x3cstrong class\x3d"fyre-archive-stream-title-icon"\x3e\x3c/strong\x3e'+z.P(a.j.mO)+'\x3c/h3\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.P(a.j.$x)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(a.j.Xo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.P(a.j.ay)+"\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e")};var IL=function(a){return(0,z.Q)('\x3cdiv class\x3d"tooltip"\x3e'+z.P(a.message)+'\x3c/div\x3e\x3cdiv class\x3d"arrow-down"\x3e\x3c/div\x3e')};var JL=function(){};var KL=function(a){this.FG=!1;this.Mo=[];this.zb=null;z.Ff.call(this,a)};var LL=function(a,b){z.Hj.call(this,b,a)};var ML=function(a,b){z.sG.call(this,a,b)};
var NL=function(a,b){var c=a.d.Jb;c.oh[4]&&(z.Bz(c,4,(0,z.r)(function(a){b.e(a,"threadBreakout",this.Nr)},a)),z.Dz(c,4,(0,z.r)(function(a){b.Ja(a,"threadBreakout",this.Nr)})))};var OL=function(a,b){var c=[a.qm,a.uz];a.yg&&c.push(a.yg);a.rt&&c.push(a.rt);a.vz&&c.push(a.vz);z.x(c,function(a){z.mk(a,"fyre-stream-sort-selected")});z.kk(b,"fyre-stream-sort-selected")};var PL=function(a,b){z.sG.call(this,a,b)};
var QL=function(a,b){z.dy.call(this,a,b);this.ah=!1;this.NI=!!this.C.L.IG;this.Ha=new z.my;this.Ha.sc(this);this.pu="archiveShowMore"};var RL=function(a,b){z.pG.call(this,a,b)};var SL=function(a,b,c){z.mu.call(this,a,b,c);this.Qz=b||"";this.wg(IL(this.s()))};var TL=function(a,b,c){z.gu.call(this,a,b||3,c)};var UL=function(a,b){z.T.call(this,b);this.l=a};var VL=function(a,b){z.T.call(this,b);this.Dc=a};var WL=function(a,b){VL.call(this,a,b)};
var XL=function(){var a=z.t.window,b=z.t.document;function c(){var a=v.elements;return"string"==typeof a?a.split(" "):a}function d(a){var b={},d=a.createElement,f=a.createDocumentFragment,g=f();a.createElement=function(a){v.tX||d(a);var c;c=b[a]?b[a].cloneNode():k.test(a)?(b[a]=d(a)).cloneNode():d(a);return c.canHaveChildren&&!h.test(a)?g.appendChild(c):c};a.createDocumentFragment=Function("h,f","return function(){var n\x3df.cloneNode(),c\x3dn.createElement;h.shivMethods\x26\x26("+c().join().replace(/\w+/g,
function(a){b[a]=d(a);g.createElement(a);return'c("'+a+'")'})+");return n}")(v,g)}function f(a){var b;if(a.wP)return a;if(v.sX&&!m){b=a.createElement("p");var c=a.getElementsByTagName("head")[0]||a.documentElement;b.innerHTML="x\x3cstyle\x3earticle,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio{display:none}canvas,video{display:inline-block;*display:inline;*zoom:1}[hidden]{display:none}audio[controls]{display:inline-block;*display:inline;*zoom:1}mark{background:#FF0;color:#000}\x3c/style\x3e";
b=!!c.insertBefore(b.lastChild,c.firstChild)}q||(b=!d(a));b&&(a.wP=b);return a}var g={},h=/^<|^(?:button|form|map|select|textarea|object|iframe)$/i,k=/^<|^(?:a|b|button|code|div|fieldset|form|h1|h2|h3|h4|h5|h6|i|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul)$/i,m,q;(function(){var c=b.createElement("a");c.innerHTML="\x3cxyz\x3e\x3c/xyz\x3e";(m="hidden"in c)&&"function"==typeof a.fU&&a.fU("#modernizr{}",function(b){b.hidden=
!0;m="none"==(a.getComputedStyle?a.getComputedStyle(b,null):b.currentStyle).display});q=1==c.childNodes.length||function(){try{b.createElement("a")}catch(a){return!0}var c=b.createDocumentFragment();return"undefined"==typeof c.cloneNode||"undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}()})();var v={elements:g.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",
shivCSS:!1!==g.sX,shivMethods:!1!==g.tX,type:"default",shivDocument:f};f(b)};var YL=function(a,b){z.AG.call(this,a,b);a.L.qP||XL();var c=a.u.Cc(),d=a.u.v();this.oi=new z.qG(a,a.Ql.xa,d.bh()||z.dg);this.F(this.oi);a.L.Sa||(this.Fn=new WL(c),this.F(this.Fn));this.Ur=new z.oG;this.F(this.Ur)};var ZL=function(a){var b=z.F.mb()||z.F.get(z.E.Ip);return!a.w.Jd()||b};var $L=function(a){z.Kz.call(this,a);this.Wm=1};
var aM=function(a){z.Zs.call(this,a);z.pv(a.u);this.Tb=new YL(a);this.ar.start();this.Gl(this.Tb);z.dt(this)};var bM=function(a,b){this.dD=LL;this.QJ=aM;z.W.lm(b.strings||{});z.Nn.call(this,a,b);this.Wa.Lb.send(z.co("Init"))};var cM=function(a){a.sk&&(a.sk.q(),delete a.sk)};z.u(DL,z.Ov);z.e=DL.prototype;z.e.sl=z.l(61);z.e.IF=z.l(63);z.e.JF=z.l(62);z.e.IF=z.K(63,function(a){this.La||(this.Io[a]=!1,z.Pv(this,a,function(a){a.N(a.ya.Vm)}))});
z.e.JF=z.K(62,function(a,b){if(!this.La){var c=this.d.u.v(),d=z.Zu(a,b),f=c.get(z.U.Mt);c.set(z.U.Gp,d.yV);z.y(d.cb,(0,z.r)(this.d.U.N,this.d.U,"bootstrap_author_received"));d.content=z.jj(d.content,function(a,b){return!z.Ua(f,b)});z.y(d.content,function(a){z.A(d.content,z.Rv(this,a))},this);z.A(this.rc,z.ij(d.content,z.Db(a)));this.be(a,d.content);z.Pv(this,a,function(b){b.N(b.ya.Jk,{Od:a});b.set(b.k.of,!0)})}});
z.e.sl=z.K(61,function(a,b){this.fl=a;this.nd=b||this.nd;var c=this.Pd[a]=new z.Kv;z.Pu.D();var d=this.d.u.v(),f=(0,z.r)(this.JF,this,a),g=(0,z.r)(this.IF,this,a),h=this.d.L.an,d=d.get(z.U.wc),h=z.w.Uu(d,h)+String(a)+".json";z.Qu(0,h,f,g);return c});z.WG.prototype.sl=z.K(60,function(a,b){this.Sk||(this.Sk=new DL(this.C));var c=this.Sk,d=CL(c,a,b);return c.sl(d,a)});z.Pu.prototype.Uh=z.K(52,function(a,b,c){a=z.xa("%s%scollection/%s/hot/",z.w.H.Ad,z.w.lf,a.na);(new z.Pe({url:a,ua:b,oa:c})).send()});
z.ew.prototype.Uh=z.K(51,function(a){var b={na:this.d.u.v().id},c=z.Pu.D().Uh;z.fw(this,c,b,a);return a});z.WG.prototype.Uh=z.K(50,function(){z.kw(this);this.Qi=new z.ew(this.C,void 0);var a=new z.Kv;this.Qi.Uh(a);return a});z.Pu.prototype.Qh=z.K(49,function(a,b,c){a=z.xa("%s%scollection/%s/top/%s/",z.w.H.Ad,z.w.lf,a.na,a.fO);(new z.Pe({url:a,ua:b,oa:c})).send({format:"stream"})});z.ew.prototype.Qh=z.K(48,function(a,b){var c={na:this.d.u.v().id,fO:a},d=z.Pu.D().Qh;z.fw(this,d,c,b);return b});
z.WG.prototype.Qh=z.K(47,function(a){z.kw(this);this.Qi=new z.ew(this.C,void 0);var b=new z.Kv;this.Qi.Qh(a,b);return b});z.T.prototype.UG=z.K(46,function(){return this.Z});z.Ej.prototype.ro=z.K(45,function(){return this.get(this.k.Fp)});z.u(JL,z.Tn);z.ca(JL);var dM={VY:"attachmentDelegate"};z.A(dM,z.nH);JL.prototype.oo=function(a){var b=JL.b.oo.call(this,a),c=a.attachmentDelegate;c&&(b.oO=c);b.Tx=a[dM.WL]||null;return b};z.u(KL,z.Ff);KL.prototype.HU=function(a){this.zb||(this.zb=z.t.setInterval((0,z.r)(this.vQ,this),5E3));this.Mo=this.Mo.concat(a)};
KL.prototype.vQ=function(){this.Mo.length&&(this.FG||(z.uc("//platform.twitter.com/impressions.js"),this.FG=!0),z.t.twttr=function(){var a=z.t.twttr||{},b=a.impressions||{};b._e=b._e||[];b.ready=b.ready||function(a){b._e.push(a)};a.impressions=b;return a}(),z.t.twttr.impressions.ready((0,z.r)(function(a){a.impressions.logTweets(this.Mo,{partner:"livefyre"});this.Mo=[]},this)))};KL.prototype.q=function(){(0,window.clearInterval)(this.zb);KL.b.q.call(this)};z.u(LL,z.Hj);LL.prototype.fz=function(a){this.Bu=new z.Xq(this,a);this.Lb=new z.Vn(this);this.Lc=new z.xi(this);this.u=new z.mv(this,a);this.hb=new z.yv(this,a);this.Nb=new z.WG(this,a);this.Ql=new z.Gv(this);new z.qf;this.cp=new z.Lw(this,a);this.Cz=new z.lw(this);this.Li=new z.Aw(this);this.Rz=new z.Ru(this,a);this.lY=new KL(this);this.Jb=new z.rz(this)};z.u(ML,z.sG);z.e=ML.prototype;z.e.s=function(){var a={},b=this.d.u,c=b.v();a.Ox=b.v().Jd();a.vV=!z.F.get(z.F.k.Xd);a.Id=b.Id(z.F.id);a.tP=2===c.get(z.U.dj);a.sP=3===c.get(z.U.dj);a.j={AU:z.W.get(z.W.g.du),DU:z.W.get(z.W.g.eu),RT:z.W.get(z.W.g.jB),$x:z.W.get(z.W.g.aq),ay:z.W.get(z.W.g.bq),Xo:z.W.get(z.W.g.kC),mp:z.W.get(z.W.g.fq),dY:z.W.get(z.W.g.CC)};return a};
z.e.K=function(a){ML.b.K.call(this,a);a=this.c;var b;b=this.s();var c=z.Q,d=z.gr(b),f;f=b.Ox?(0,z.Q)('\x3ca class\x3d"fyre-follow-conversation"\x3e'+(b.vV?b.Id?z.P(b.j.DU):z.P(b.j.AU):"")+"\x3c/a\x3e"):"";b=c(d+f+'\x3cdiv class\x3d"fyre-stream-sort"\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.P(b.j.$x)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(b.j.Xo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.P(b.j.ay)+"\x3c/a\x3e"+(b.tP?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(b.j.Xo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-top-comments"\x3e'+z.P(b.j.dY)+"\x3c/a\x3e":"")+(b.sP?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(b.j.Xo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-hot-threads"\x3e'+z.P(b.j.RT)+"\x3c/a\x3e":"")+'\x3c/div\x3e\x3ca class\x3d"fyre-stream-sort-back"\x3e\x3c/a\x3e\x3c/div\x3e');a.innerHTML=b;this.rl=this.o("fyre-follow-conversation");this.rt=this.o("fyre-stream-sort-hot-threads")||
null;this.vz=this.o("fyre-stream-sort-top-comments")||null;this.yg=this.o("fyre-stream-sort-back");this.qm=this.o("fyre-stream-sort-newest");this.uz=this.o("fyre-stream-sort-oldest");this.TI=this.o("fyre-stream-sort-options");this.bd=this.o("fyre-content-loading");this.Gd()};z.e.m=function(){ML.b.m.call(this);var a=this.p();z.F.on(z.F.ya.Vf,this.ho,this);a.e(this.c,"click",this.lb);z.x([3,4,5],function(b){z.tG(this,a,b)},this);NL(this,a)};
z.e.lb=function(a){a.preventDefault();a=a.target;if(!z.qk(a,"fyre-stream-sort-selected")&&"A"===a.tagName&&a!==this.yg)if(a===this.rl)this.GF();else{OL(this,a);this.pm();var b=null;switch(a){case this.rt:this.rE();b="hottest";break;case this.vz:this.dispatchEvent({type:"sortTopComments",Xb:(0,z.r)(this.Gd,this)});b="top_comments";break;case this.qm:this.un("new");b="newest";break;case this.uz:this.un("old"),b="oldest"}this.d.Lb.send(z.co("SortStream",{Cs:b}))}};
z.e.Hi=function(a,b){a&&this.gz(b);z.Cl(this.TI,"display",a?"none":"block");z.Cl(this.yg,"display",a?"block":"none")};z.e.gz=function(a){var b=this.qm,c=this.un,d=z.W.get(z.W.g.Nt);4===a&&(b=this.rt,c=this.rE,d=z.W.get(z.W.g.eK));this.yg.innerHTML=d;this.p().Kd(this.yg,"click",(0,z.r)(function(a){a.stopPropagation();this.Hi(!1);OL(this,b);c.apply(this)},this))};z.e.bo=function(a){a.stopPropagation();this.Hi(!1);OL(this,this.qm);this.un()};
z.e.Nr=function(a){var b=a.Xb;z.A(a,{Xb:(0,z.r)(function(){b();this.Hi(!0,4)},this)})};z.e.un=function(a){this.dispatchEvent({type:"sortOrderChanged",direction:a||"new",Xb:(0,z.r)(this.Gd,this)})};z.e.rE=function(){this.dispatchEvent({type:"sortHotThreads",Xb:(0,z.r)(this.Gd,this)})};z.e.GF=function(){var a=this.d.u;a.v();var b=z.F.k;z.F.id?(b=a.Id(z.F.get(b.X)),a.Cj(!b),a=b?z.W.get(z.W.g.du):z.W.get(z.W.g.eu),this.rl.innerHTML=a):z.Sh(this.d.Lc,(0,z.r)(this.GF,this))};
z.e.ho=function(){var a=this.d.u,b=a.v(),c=z.F.k,b=!b.Jd()||z.F.get(c.Xd);this.rl&&(b?z.N(this.rl,!1):(a=a.Id(z.F.id)?z.W.get(z.W.g.eu):z.W.get(z.W.g.du),this.rl.innerHTML=a,z.N(this.rl,!0)))};z.e.h=function(){ML.b.h.call(this);z.F.off(null,null,this)};z.u(PL,ML);PL.prototype.K=function(a){this.c=a;z.zo(a,HL,this.s());this.qm=this.o("fyre-stream-sort-newest");this.uz=this.o("fyre-stream-sort-oldest");this.TI=this.o("fyre-stream-sort-options");this.bd=this.o("fyre-content-loading");this.Gd()};PL.prototype.un=function(a){this.dispatchEvent({type:"archiveSortOrderChanged",stream:this.QX.stream,direction:a,Xb:(0,z.r)(this.Gd,this)})};
PL.prototype.s=function(){return{j:{mO:z.W.get(z.W.g.$J),$x:z.W.get(z.W.g.aq),ay:z.W.get(z.W.g.bq),Xo:z.W.get(z.W.g.kC),mp:z.W.get(z.W.g.fq)}}};z.u(QL,z.dy);z.e=QL.prototype;z.e.jn=function(a){this.clear();z.N(this.c,!0);this.nd=a};z.e.clear=function(){this.ld.Lf();this.Ab={};this.Jj=[];for(this.ph=this.Wk=null;this.ma&&0!=this.ma.length;)this.Po(0).q()};z.e.K=function(a){QL.b.K.call(this,a);z.zo(this.c,z.hr,this.s());this.kk=this.o("fyre-stream-content");this.Ii=this.o("fyre-stream-more");this.Ha.S(this.Ii);z.N(this.Ii,!1)};z.e.h=function(){this.Ha&&this.Ha.q();this.Ha=null;QL.b.h.call(this)};
z.e.m=function(){QL.b.m.call(this);this.p().e(this.Ha,"showMore",this.Yw)};z.e.bw=function(){return this.C.L.IG};z.e.s=function(){return{ce:z.w.H.ob,rv:!!this.Ha,j:{mz:z.W.get(z.W.g.aK)}}};z.e.Zw=function(){this.Ha.mt();this.ah=!0};z.e.ry=function(){this.dispatchEvent({type:this.pu,direction:this.nd,target:this,tY:this.ah&&this.NI,Xb:(0,z.r)(this.Zw,this),Bj:(0,z.r)(this.fG,this)});this.ah&&(this.NI=!1)};z.e.yy=function(a){this.ah||QL.b.yy.call(this,a)};
z.e.bp=function(){var a=this.C.Nb.Sk,b=this.nd,c=a.d.u.v(),b="old"===b,c=c.get(z.U.Gp),c=!b&&a.fl>-c;b&&-1>a.fl||c?this.Ha.show():this.Ha.rb()};z.e.start=function(){this.ah||this.ry()};z.u(RL,z.pG);var eM=z.W.g,fM={};fM.comment=[eM.Qm,eM.Wf,eM.Fm];fM.liveblog=[eM.yM,eM.KL,eM.pB];RL.prototype.cF=function(a){function b(a){return z.Ha(a,"%s")?a:"%s "+a}var c=this.l.Jd()?"liveblog":"comment",c=fM[c];switch(a){case 1:c=b(z.W.get(c[1]));break;case 0:if(z.W.get(c[0])!==z.nG[c[0]]){c=z.W.get(c[0]);break}default:c=b(z.W.get(c[2]))}return z.xa(c,a)};z.u(SL,z.mu);SL.prototype.ep=200;SL.prototype.Wh=function(){return new TL(this.Kc)};SL.prototype.s=function(){var a={};a.message=this.Qz;return a};z.u(TL,z.gu);TL.prototype.Pc=function(a,b,c){var d=z.am(this.element),d=new z.Ch(d.width,d.height+25);b=z.bu(this.element,this.Jh,a,b,d,c,9);z.Il(a.lastChild,0);b&&(d=new z.Ch(0,-5),z.bu(this.element,2,a,1,d,c,5),z.Il(a.lastChild,a.offsetWidth-(this.element.offsetParent.offsetWidth-this.element.offsetLeft+this.element.offsetWidth/2)))};z.u(UL,z.T);z.e=UL.prototype;z.e.r=function(){this.c=z.Co(GL,this.s())};z.e.m=function(){UL.b.m.call(this);this.Va=new SL(this.c,this.l.get("displayName"));this.p().e(this.c,"click",this.lb)};z.e.h=function(){UL.b.h.call(this);this.Va&&this.Va.q()};z.e.s=function(){var a=z.Vd,b={};b.zd=this.l.get(a.xb);b.cc=this.l.get(a.yk);b.da=this.l.get(a.va);b.id=this.l.id;b.TT=this.l.id.replace(/[@.]/g,"-");b.Aa=this.l.get(a.Zb);return b};
z.e.lb=function(a){a.preventDefault();a.stopPropagation();this.dispatchEvent({t:this.l,type:"author_click"})};z.u(VL,z.T);z.e=VL.prototype;z.e.tB=10;z.e.h=function(){VL.b.h.call(this);delete this.Dc};z.e.Q=function(){VL.b.Q.call(this);this.Dc.off(null,null,this)};z.e.qF=function(a){a=new UL(a);var b=this.Nc();if(b===this.tB){var c=this.Po(b-1);c&&(c.q(),b--)}0<b?this.He(a,0,!0):this.F(a,!0)};z.e.WS=function(a){var b;this.Wc(function(c){a.id===c.l.id&&(b=c)});b&&(this.removeChild(b),b.q())};
z.e.co=function(){this.Dc.on(this.Dc.ya.Lt,this.qF,this);this.Dc.on(this.Dc.ya.lu,this.WS,this);var a=this.Dc.sb.reverse().slice(0,this.tB);z.x(a,this.qF,this)};z.u(WL,VL);z.u(YL,z.AG);
YL.prototype.jI=function(a,b){if(!this.La){this.w=b;var c=b.get(z.U.yh),d=b.get(z.U.Zd);this.Ft=new z.xG(c,d,a.L.Sa);this.F(this.Ft);this.Lq=new RL(a.u.v());this.F(this.Lq);this.ys=null;b.ro()&&(this.Mu=new PL(a),this.F(this.Mu),this.Tk=new QL(a),this.F(this.Tk),EL(this.Mu,{stream:this.Tk}));this.mh=new ML(a);this.F(this.mh);this.qs((0,z.r)(function(a){this.dc=a;this.F(this.dc);a=this.dc;this.Z&&a&&a.S(this.ke,!0)},this));b.get(z.U.Lm)&&!z.dg&&this.w.hr()&&(this.w.bh()||this.w.Jd()||this.Ew())}};
YL.prototype.s=function(){return{Sa:this.d.L.Sa,bh:this.w.bh(),Jd:this.w.Jd(),se:z.dg,kU:this.d.L.mD,ro:this.w.ro()}};z.sy={RY:"fyre-archive-stream",SY:"fyre-archive-stream-header",J1:"fyre-top-content-stream",c2:"fyre-widget",Lm:"fyre-featured-content-wrapper"};z.A(z.sy,z.nK);z.e=YL.prototype;
z.e.r=function(){this.c=z.Co(FL,this.s());var a=this.w.get(z.U.dj);if(1!==a){var b=this.d.Jb,a=2===a?3:4,c=this.o("fyre-top-content-stream");z.sz(b,a,c,this)}this.Ur.S(this.o(z.sy.vL));this.Tk&&(b=this.o("fyre-archive-stream-header"),this.Mu.S(b),this.Tk.S(this.o("fyre-archive-stream")));this.Kh(1);this.ke=this.o(z.sy.vh);b=ZL(this);z.N(this.ke,b)};
z.e.m=function(){YL.b.m.call(this);var a=this.dc;this.Z&&a&&a.S(this.ke,!0);this.d.U.op("stream_data_received",this.UR,this);this.p().e(this,"request_content_context",this.rR).e(this,"request_content_reply",this.ZS);this.Tk&&this.Tk.start()};z.e.co=function(){this.Fn&&this.Fn.co()};z.e.UR=function(){var a=this.w,b=a.get(z.U.Ck);z.th||b||(b=(0,z.r)(function(){this.ys=new z.gM(this.d,a.get(z.U.Zd));this.F(this.ys,!0)},this),z.uc(z.w.H.ob+z.w.Gf.ys,null,null,b))};
z.e.Ew=function(){var a=new z.gF(this.UG,this);a.KH=(0,z.r)(this.OW,this);var b=(0,z.r)(function(){a.start(0,2E3)},this);z.uc(z.w.H.ob+z.w.Gf.ZP,null,null,b)};z.e.OW=function(){var a=this.o("fyre-featured-content-wrapper");this.Lv=new z.DK(this.d);this.F(this.Lv);this.Lv.S(a);this.Lv.$g()};z.e.qs=function(a){if(!this.d.L.readOnly){var b=this.d.u.v();z.gx(z.dx.D(),"main",a,{C:this.d,zi:"new"},b);z.F.on(z.F.mc(z.F.k.X),this.Xc,this)}};z.e.Xc=function(){if(this.ke){var a=ZL(this);z.N(this.ke,a)}};
z.e.ai=function(){0<z.Ip(this,this.dc)&&(this.removeChild(this.dc),this.dc.q());this.qs((0,z.r)(function(a){this.dc=a;this.F(this.dc);a=this.dc;this.Z&&a&&a.S(this.ke,!0);z.N(this.ke,!0)},this))};z.e.Zg=function(a,b){null!=a&&(this.d.Jb.wl(1),(0,window.setTimeout)((0,z.r)(function(){var c=b&&function(a){z.cx(a.Xa)};this.La||z.BG(this,a,c)},this),3E3))};z.e.rR=function(a){z.BG(this,a.$k)};z.e.ZS=function(a){z.BG(this,a.$k,function(a){z.cx(a.Xa)})};
z.e.h=function(){YL.b.h.call(this);z.F.off(z.F.mc(z.F.k.X),this.Xc,this);this.w&&(this.w.off(null,null,this),this.w=null)};z.u($L,z.Kz);z.e=$L.prototype;z.e.pe=function(a,b){$L.b.pe.call(this,a,b);a.e(b,"repliesExpanded",this.DF);a.e(b,"sortHotThreads",this.kT);a.e(b,"sortOrderChanged",this.iG);a.e(b,"sortTopComments",this.lT);a.e(b,"archiveShowMore",this.aR);a.e(b,"archiveSortOrderChanged",this.bR)};
z.e.aR=function(a){var b=a.Xb||z.n,c=(0,z.r)(this.Te,this,a.target),d=this.d.Nb;a=a.tY;d.Sk||(d.Sk=new DL(d.C));d=d.Sk;a=a?d.fl:CL(d);var f=d.cd[a];f&&(d.fl=a);if(f)b(),c(f);else{d=this.d.Nb.sl();a=d.k.of;if(d.get(a))b();else d.on(d.mc(a),b,this);z.Lz(this,d,c)}};z.e.zw=function(a,b){var c=2===b.dd,d=1!==b.dd;switch(b.type){case 0:var f=this.d.u.v(),f=z.Mm(b,f),g=f.get(z.an),g=this.d.u.cb().get(g);f.set(z.Nm,g);a.Qw(f,c,d)}};
z.e.aG=function(a){if(1!==this.Wm){var b=this.IX.mh;b.Hi(!1);OL(b,b.qm);z.A(a,{direction:"new",Xb:z.n});this.iG(a)}};z.e.bR=function(a){z.Mz(this);a.stream.jn(a.direction);var b=this.d.Nb.sl(a.direction,!0),c=(0,z.r)(function(b){a.Xb();this.Te(a.stream,b)},this);z.Lz(this,b,c,a.Bj)};z.e.iG=function(a){this.d.L.gi=null;var b=z.Oz(this,1);z.kw(this.d.Nb);b.jn(a.direction);var c=z.jw(this.d.Nb,a.direction),d=(0,z.r)(function(c){a.Xb();this.Te(b,c)},this);z.Lz(this,c,d,a.Bj)};
z.e.lT=function(a){var b=z.Oz(this,3),c=this.d.Nb.Qh("likes");z.Lz(this,c,(0,z.r)(function(c){a.Xb();z.ib(c)?z.cy(b):this.Te(b,c)},this))};z.e.kT=function(a){var b=z.Oz(this,4),c=this.d.Nb.Uh();z.Lz(this,c,(0,z.r)(function(c){a.Xb();z.ib(c)?z.cy(b):this.Te(b,c)},this))};z.u(aM,z.Zs);z.e=aM.prototype;z.e.c=null;z.e.h=function(){aM.b.h.call(this);this.tt.q();this.GD.q();this.Tb.Z&&this.Tb.q();this.Tf&&this.Tf.q();delete this.Tf};z.e.Gl=function(a){aM.b.Gl.call(this,a);this.tt=new $L(this.d);this.tt.handle(a);this.GD=new z.Hz(this.d);this.GD.handle(a)};z.e.Dz=function(){this.d.Li.stop()};z.e.PX=function(){this.d.Ql.stop()};z.e.hk=function(){this.d.Li.start()};z.e.MX=function(){this.d.Ql.start()};
z.e.ra=function(){this.Tf&&this.Tf.q();this.Tb.ra(this.c);this.d.Lb.send(z.co("Load"));var a=z.at(window.location,"reply_editor");if("object"===typeof window.Livefyre&&window.Livefyre.YN)z.et(this,a);else{var b=z.bt(this);this.Tb.Zg(b,a)}this.d.U.N("render_complete",this.c)};z.u(bM,z.Nn);bM.prototype.ZC=JL.D();bM.prototype.h=function(){bM.b.h.call(this);this.stop();delete this.L;delete this.ha;cM(this);z.Sn(this);this.Aj&&(this.Aj.q(),delete this.Aj)};bM.prototype.Lz=function(){this.stop();cM(this);bM.b.Lz.call(this)};z.lg.main.Mh.ia(bM);})(fyre.conv);
